-- ============================================
-- 04 WEBSITE ANALYSIS
-- E-commerce Business Analytics
-- Database: ecommerce_analytics
-- ============================================
--
-- Purpose:
-- Analyze website traffic, device performance,
-- page popularity, and marketing-source activity.
-- ============================================


-- 1. Website sessions by month
-- Measures how website traffic changed over time.

SELECT
    DATE_TRUNC('month', created_at) AS month,
    COUNT(*) AS sessions
FROM website_sessions
GROUP BY DATE_TRUNC('month', created_at)
ORDER BY month;


-- 2. Sessions and orders by device
-- Compares website conversion performance between devices.

SELECT
    ws.device_type,
    COUNT(DISTINCT ws.website_session_id) AS sessions,
    COUNT(DISTINCT o.order_id) AS orders,
    ROUND(
        COUNT(DISTINCT o.order_id) * 100.0
        / NULLIF(COUNT(DISTINCT ws.website_session_id), 0),
        2
    ) AS conversion_rate_pct
FROM website_sessions ws
LEFT JOIN orders o
    ON ws.website_session_id = o.website_session_id
GROUP BY ws.device_type
ORDER BY conversion_rate_pct DESC;


-- 3. Most visited pages
-- Identifies the pages receiving the most traffic.

SELECT
    pageview_url,
    COUNT(*) AS pageviews
FROM website_pageviews
GROUP BY pageview_url
ORDER BY pageviews DESC
LIMIT 15;


-- 4. Website sessions by marketing source
-- Measures the amount of traffic generated by each source.
-- Handles both SQL NULL values and literal 'NULL' values.

SELECT
    CASE
        WHEN utm_source IS NULL OR utm_source = 'NULL'
            THEN 'Direct / Unknown'
        ELSE utm_source
    END AS channel,
    COUNT(*) AS sessions
FROM website_sessions
GROUP BY
    CASE
        WHEN utm_source IS NULL OR utm_source = 'NULL'
            THEN 'Direct / Unknown'
        ELSE utm_source
    END
ORDER BY sessions DESC;


-- 5. Marketing channel conversion
-- Compares traffic volume with order conversion by channel.

SELECT
    CASE
        WHEN ws.utm_source IS NULL OR ws.utm_source = 'NULL'
            THEN 'Direct / Unknown'
        ELSE ws.utm_source
    END AS channel,
    COUNT(DISTINCT ws.website_session_id) AS sessions,
    COUNT(DISTINCT o.order_id) AS orders,
    ROUND(
        COUNT(DISTINCT o.order_id) * 100.0
        / NULLIF(COUNT(DISTINCT ws.website_session_id), 0),
        2
    ) AS conversion_rate_pct
FROM website_sessions ws
LEFT JOIN orders o
    ON ws.website_session_id = o.website_session_id
GROUP BY
    CASE
        WHEN ws.utm_source IS NULL OR ws.utm_source = 'NULL'
            THEN 'Direct / Unknown'
        ELSE ws.utm_source
    END
ORDER BY conversion_rate_pct DESC;