-- ============================================
-- 06 MARKETING CHANNEL ANALYSIS
-- E-commerce Business Analytics
-- Database: ecommerce_analytics
-- ============================================
--
-- Purpose:
-- Evaluate marketing channel performance using
-- traffic, orders, conversion rate, revenue,
-- average order value, and yearly performance.
-- ============================================


-- 1. Sessions by marketing channel
-- Measures the amount of website traffic generated
-- by each marketing channel.
-- Handles both SQL NULL values and literal 'NULL' values.

SELECT
    CASE
        WHEN utm_source IS NULL OR utm_source = 'NULL'
            THEN 'Direct / Unknown'
        ELSE utm_source
    END AS channel,
    COUNT(*) AS sessions
FROM website_sessions
GROUP BY
    CASE
        WHEN utm_source IS NULL OR utm_source = 'NULL'
            THEN 'Direct / Unknown'
        ELSE utm_source
    END
ORDER BY sessions DESC;


-- 2. Sessions, orders and conversion by channel
-- Compares traffic volume with the number of orders
-- generated by each marketing channel.

SELECT
    CASE
        WHEN ws.utm_source IS NULL OR ws.utm_source = 'NULL'
            THEN 'Direct / Unknown'
        ELSE ws.utm_source
    END AS channel,
    COUNT(DISTINCT ws.website_session_id) AS sessions,
    COUNT(DISTINCT o.order_id) AS orders,
    ROUND(
        COUNT(DISTINCT o.order_id) * 100.0
        / NULLIF(COUNT(DISTINCT ws.website_session_id), 0),
        2
    ) AS conversion_rate_pct
FROM website_sessions ws
LEFT JOIN orders o
    ON ws.website_session_id = o.website_session_id
GROUP BY
    CASE
        WHEN ws.utm_source IS NULL OR ws.utm_source = 'NULL'
            THEN 'Direct / Unknown'
        ELSE ws.utm_source
    END
ORDER BY conversion_rate_pct DESC;


-- 3. Revenue by marketing channel
-- Identifies which channels generate the most revenue.

SELECT
    CASE
        WHEN ws.utm_source IS NULL OR ws.utm_source = 'NULL'
            THEN 'Direct / Unknown'
        ELSE ws.utm_source
    END AS channel,
    COUNT(DISTINCT o.order_id) AS orders,
    ROUND(SUM(o.price_usd), 2) AS revenue
FROM website_sessions ws
LEFT JOIN orders o
    ON ws.website_session_id = o.website_session_id
GROUP BY
    CASE
        WHEN ws.utm_source IS NULL OR ws.utm_source = 'NULL'
            THEN 'Direct / Unknown'
        ELSE ws.utm_source
    END
ORDER BY revenue DESC;


-- 4. Average order value by marketing channel
-- Measures the average revenue generated per order
-- for each marketing channel.

SELECT
    CASE
        WHEN ws.utm_source IS NULL OR ws.utm_source = 'NULL'
            THEN 'Direct / Unknown'
        ELSE ws.utm_source
    END AS channel,
    COUNT(DISTINCT o.order_id) AS orders,
    ROUND(
        SUM(o.price_usd)
        / NULLIF(COUNT(DISTINCT o.order_id), 0),
        2
    ) AS average_order_value
FROM website_sessions ws
LEFT JOIN orders o
    ON ws.website_session_id = o.website_session_id
GROUP BY
    CASE
        WHEN ws.utm_source IS NULL OR ws.utm_source = 'NULL'
            THEN 'Direct / Unknown'
        ELSE ws.utm_source
    END
ORDER BY average_order_value DESC;


-- 5. Marketing channel performance by year
-- Tracks channel traffic, orders, conversion,
-- and revenue over time.

SELECT
    EXTRACT(YEAR FROM ws.created_at) AS year,
    CASE
        WHEN ws.utm_source IS NULL OR ws.utm_source = 'NULL'
            THEN 'Direct / Unknown'
        ELSE ws.utm_source
    END AS channel,
    COUNT(DISTINCT ws.website_session_id) AS sessions,
    COUNT(DISTINCT o.order_id) AS orders,
    ROUND(
        COUNT(DISTINCT o.order_id) * 100.0
        / NULLIF(COUNT(DISTINCT ws.website_session_id), 0),
        2
    ) AS conversion_rate_pct,
    ROUND(SUM(o.price_usd), 2) AS revenue
FROM website_sessions ws
LEFT JOIN orders o
    ON ws.website_session_id = o.website_session_id
GROUP BY
    EXTRACT(YEAR FROM ws.created_at),
    CASE
        WHEN ws.utm_source IS NULL OR ws.utm_source = 'NULL'
            THEN 'Direct / Unknown'
        ELSE ws.utm_source
    END
ORDER BY year, revenue DESC;